address: tcp://*:5555
max_batch_size: 1
max_batch_latency: 80

models:
  yolov3:
    num_workers: 1

    xmodel: /usr/share/vitis_ai_library/models/yolov3_voc/yolov3_voc.xmodel

    input_width: 416
    input_height: 416

    anchor_boxes: 3
    classes: 20

    biases: [10,13,16,30,33,23, 30,61,62,45,59,119, 116,90,156,198,373,326]
    labels: [aeroplane, bicycle, bird, boat, bottle, bus, car, cat, chair, cow,
             diningtable, dog, horse, motorbike, person, pottedplant, sheep, sofa, train, tvmonitor]
