address: tcp://*:5555
num_threads: 16

models:
  yolov3:
    xmodel:  model/yolov3.xmodel

    num_runners: 4
    num_streams: 8

    inputs:
      input:
        layer: data
        shape: [608, 608, 3]

    outputs:
      output:
        layer: layer31-conv
        shape: [19, 19, 425]
